steps:
  - name: node
  entrypoint: npm
  args: ['install']
  
  # prod build
  - name: node
  entrypoint: npm
  args: ['run', 'build']
  
  # build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/webstore-frontend:$COMMIT_SHA', '.']

  # push the container image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/webstore-frontend:$COMMIT_SHA']

  # deploy to cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'webstore-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/webstore:$COMMIT_SHA'
      - '--region'
      - 'europe-north1'
images:
  - 'gcr.io/$PROJECT_ID/webstore-frontend:$COMMIT_SHA'
